### ISSUE TITLE
BEAM

### ISSUE THREAD

**Issue by darionyaphet** [lw-lin/streaming-readings#2]
感觉Apache Beam有机会成为统一Batch与Streaming的接口  如果有paper的话可以收录一下么？

**Comment by lw-lin** [comment]
@darionyaphet 呃，已经收录在 2015 年里的 paper 里了：
> The Dataflow Model: A Practical Approach to Balancing Correctness, Latency, and Cost in Massive-Scale, Unbounded, Out-of-Order Data Processing (VLDB): 来自 Google 的将 stream processing 模型和 batch processing 模型统一的尝试。在 Dataflow model 下，底层依赖 FlumeJava 支持 batch processing，依赖 MillWheel 支持 stream processing。Dataflow model 的开源实现是 Apache Beam 项目。

**Comment by darionyaphet** [comment]
:+1:
